[package]
name = "unreal-api"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy_ecs = "0.7"
glam = "0.20.2"
log = { version = "0.4.14", features =["std"] }
unreal-reflect= { path = "../unreal-reflect" }
unreal-ffi= { path = "../unreal-ffi" }
