[package]
name = "unreal-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.5"
glam = "0.20.2"
log = { version = "0.4.14", features =["std"] }
[build-dependencies]
cbindgen = "0.20"