[package]
name = "unreal-ffi"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.7"
glam = "0.20.2"

[build-dependencies]
cbindgen = "0.20"
